# NUMPY
1. Array oluşturma

In [1]:
import numpy as np

In [2]:
a=np.array([1,2,3,4,5])

In [3]:
type(a)

numpy.ndarray

In [4]:
np.arange(0,31,3)

array([ 0,  3,  6,  9, 12, 15, 18, 21, 24, 27, 30])

In [9]:
np.random.normal(10,4,(2,2)) # ortalaması 10, standart sapması 4 olan iki satır iki sütunluk rastgele değerler alan bir matris

array([[13.21421867,  8.73959776],
       [12.87286249, 10.57024976]])

In [10]:
np.random.randint(0, 10, (3,3))

array([[4, 1, 6],
       [5, 5, 7],
       [0, 4, 6]])