# Reshaping(Yeniden Şekilllendirme)


In [3]:
import numpy as np

In [4]:
np.arange(1, 10)

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [8]:
np.arange(1, 10).reshape((3,3)) # tek boyutlu bir matrisi 3x3 lük bir matrise dönüştürdük

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [10]:
a = np.arange(1, 10)
a

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [11]:
a.ndim

1

In [16]:
b = a.reshape((1,9))
b

array([[1, 2, 3, 4, 5, 6, 7, 8, 9]])

*a ve b değişkenleri aslında aynıdır fakat a değişkenin shape bilgisi 1 olarak tutulurken, b değişkeninin shape değişkeni 2 olarak tutulur bunun sebebi*
*b değişkeni reshape metodu kullanılarak bir matrise dönüştürülmüştür*